#!/bin/sh
#  Program:   Insight Segmentation & Registration Toolkit
#  Module:    testScript
#  Language:  C++
#  Date:      $Date$
#  Version:   $Revision$
#
#  Copyright (c) 2002 Insight Consortium. All rights reserved.
#  See ITKCopyright.txt or http://www.itk.org/HTML/Copyright.htm for details.
#
#     This software is distributed WITHOUT ANY WARRANTY; without even 
#     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
#     PURPOSE.  See the above copyright notices for more information.

# This script assumes that it's running in the build directory for
# InverseConsistentRegistration, if not, you need to edit in the proper
# path


if [ $# == 0 ] ; then echo need source directory for CLReg as parameter ; fi

./CLReg $1/TestInputs/grids.hdr $1/TestInputs/grids.hdr \
        $1/TestInputs/set1.lmk $1/TestInputs/set2.lmk

./CLRegTest $1/BaselineResults .
